# Generated by Django 4.2.2 on 2023-06-20 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_remove_currency_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Название сайта')),
                ('phone', models.BigIntegerField(blank=True, max_length=155, null=True, verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта')),
                ('address', models.CharField(max_length=155, verbose_name='Адрес')),
                ('logo', models.ImageField(upload_to='logo/', verbose_name='Логотип сайта')),
                ('tittle', models.TextField(max_length=155, verbose_name='Заголовок сайта')),
                ('description', models.TextField(max_length=155, verbose_name='Описание сайта')),
            ],
            options={
                'verbose_name': 'Настройка сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
    ]
